server:
  port: 3001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: carellano
    password: 23people
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka
    healthcheck:
      enabled: true
